### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by scottsuch** [giancarlogarcia/jenkins-victorops-plugin#1]
The plugin asks for two configurations:
`Server url` and `API key`
What information goes in those fields? In my victorops integrations page I have the following setup:
![screenshot_2015-11-11_13_46_18](https://cloud.githubusercontent.com/assets/897179/11099693/c9980504-887a-11e5-984b-83bcd99ff4a7.png)
I assume they part i've blurred is the API key?

Thanks in advance.

**Comment by scottsuch** [comment]
After digging around a bit I got this working (I'm not super familiar with Java). However for those looking, the Server url should just be `alert.victorops.com` and the API key was just the blurred out bit. Thanks for this plugin, works like a charm!

**Comment by giancarlogarcia** [comment]
Thanks! Glad you got it working.
